import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import ReactQueryProvider from "@components/utils/reactQueryProvider";
import GlobalStoreWrapper from "@components/utils/GlobalStoreWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-2 mb-4">
          <Link href="/">Home</Link>
          <Link href="/another">another</Link>
        </div>
        <ReactQueryProvider>
          <GlobalStoreWrapper>
            <div className="m-4">{children}</div>
          </GlobalStoreWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
